web:
  upload-path: E:/downloads/images/
spring:
  application:
    name: system-admin
  zipkin:
    base-url: http://localhost:9014
  datasource:
    druid:
      url: jdbc:mysql://10.211.55.4:3306/kyb?useSSL=false&characterEncoding=utf-8&autoReconnect=true
      username: yangzhenze
      password: yangzhenze6712
      initial-size: 5 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      max-active: 1500 #最大连接池数量
      min-idle: 1  #最小连接池数量
      max-wait: 60000  #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      filter:
        stat:
          log-slow-sql: true #sql
          slow-sql-millis: 2000 #\u6162sql\u8BB0\u5F55
      filters: stat,wall
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 60000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT1FROMDUAL
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，配置true会降低性能。
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，配置true会降低性能
      remove-abandoned: true #对于长时间不使用的连接强制关闭
      remove-abandoned-timeout: 1800 #关闭超过30分钟的空闲连接，1800秒，也就是30分钟
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
server:
  port: 9012
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
